### PR TITLE
Added niklo which represents break - needs testing

### PR DESCRIPTION
**Pull request by mzaidikhlas**

### CODE REVIEW

**Comment by mdanishs** [comment]
`niklo` would be better as `rukjao` i think

**Comment by asadm** [comment]
ruko, rukjao, roko. Hard to decide on one.

**Comment by mzaidikhlas** [comment]
If we are going with this, i think we should go for `ruko` because the impressiveness aligns with `likho` and `karo`

**Comment by asadm** [comment]
is `ruko` intuitive to you guys? Does it feel natural, in this code for example:
```js
milgya = khali
har list k naam per {
   agar(naam==="Ali") { 
     milgya = naam
     ruko;
  }
}
```

compared to `rukjao`
```js
milgya = khali
har list k naam per {
   agar(naam==="Ali") { 
     milgya = naam
     rukjao;
  }
}
```

**Comment by mzaidikhlas** [comment]
Ok, on a second thought, `rukjao` feels more natural while reading the code. 
`ruko` feels a bit more like a pause or a [yield](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/yield) to be more specific

**Comment by asadm** [comment]
I think we can settle on `rukjao` for now. Can you update the PR. I will merge.

Also, can you add `"rukjao": C,` [here](https://github.com/asadm/urduscript/blob/master/docs/editor/mode/urduscript/urduscript.js#L50) to add syntax highlighting support in the editor.

**Comment by aitchkhan** [comment]
why there are so many huge changes in each file? did you change the indentation?  
This not a good practice though

**Comment by asadm** [comment]
Yeah I was wondering that too in the diff.

**Pull request closed without merging**
